
export const FilmGenres = [
    'Drama', 'Action', 'Crime', 'Thriller', 'Mystery', 'Science Fiction', 'Fantasy', 'Adventure'
]

export const TranslationTypes = [
    { text: 'Dubbing', id: 'dub' },
    { text: 'Subbing', id: 'sub' },
    { text: 'Subbing + Dubbing', id: 'sub+dub' },
]

export const Professions = [
    'Director', 'Actor'
]
export const Languages = [
    {text: "Afrikaans", id: "af"},
    {text: "Albanian - shqip", id: "sq"},
    {text: "Amharic - አማርኛ", id: "am"},
    {text: "Arabic - العربية", id: "ar"},
    {text: "Aragonese - aragonés", id: "an"},
    {text: "Armenian - հայերեն", id: "hy"},
    {text: "Asturian - asturianu", id: "ast"},
    {text: "Azerbaijani - azərbaycan dili", id: "az"},
    {text: "Basque - euskara", id: "eu"},
    {text: "Belarusian - беларуская", id: "be"},
    {text: "Bengali - বাংলা", id: "bn"},
    {text: "Bosnian - bosanski", id: "bs"},
    {text: "Breton - brezhoneg", id: "br"},
    {text: "Bulgarian - български", id: "bg"},
    {text: "Catalan - català", id: "ca"},
    {text: "Central Kurdish - کوردی (دەستنوسی عەرەبی)", id: "ckb"},
    {text: "Chinese - 中文", id: "zh"},
    {text: "Chinese (Hong Kong) - 中文（香港）", id: "zh-HK"},
    {text: "Chinese (Simplified) - 中文（简体）", id: "zh-CN"},
    {text: "Chinese (Traditional) - 中文（繁體）", id: "zh-TW"},
    {text: "Corsican", id: "co"},
    {text: "Croatian - hrvatski", id: "hr"},
    {text: "Czech - čeština", id: "cs"},
    {text: "Danish - dansk", id: "da"},
    {text: "Dutch - Nederlands", id: "nl"},
    {text: "English", id: "en"},
    {text: "English (Australia)", id: "en-AU"},
    {text: "English (Canada)", id: "en-CA"},
    {text: "English (India)", id: "en-IN"},
    {text: "English (New Zealand)", id: "en-NZ"},
    {text: "English (South Africa)", id: "en-ZA"},
    {text: "English (United Kingdom)", id: "en-GB"},
    {text: "English (United States)", id: "en-US"},
    {text: "Esperanto - esperanto", id: "eo"},
    {text: "Estonian - eesti", id: "et"},
    {text: "Faroese - føroyskt", id: "fo"},
    {text: "Filipino", id: "fil"},
    {text: "Finnish - suomi", id: "fi"},
    {text: "French - français", id: "fr"},
    {text: "French (Canada) - français (Canada)", id: "fr-CA"},
    {text: "French (France) - français (France)", id: "fr-FR"},
    {text: "French (Switzerland) - français (Suisse)", id: "fr-CH"},
    {text: "Galician - galego", id: "gl"},
    {text: "Georgian - ქართული", id: "ka"},
    {text: "German - Deutsch", id: "de"},
    {text: "German (Austria) - Deutsch (Österreich)", id: "de-AT"},
    {text: "German (Germany) - Deutsch (Deutschland)", id: "de-DE"},
    {text: "German (Liechtenstein) - Deutsch (Liechtenstein)", id: "de-LI"},
    {text: "German (Switzerland) - Deutsch (Schweiz)", id: "de-CH"},
    {text: "Greek - Ελληνικά", id: "el"},
    {text: "Guarani", id: "gn"},
    {text: "Gujarati - ગુજરાતી", id: "gu"},
    {text: "Hausa", id: "ha"},
    {text: "Hawaiian - ʻŌlelo Hawaiʻi", id: "haw"},
    {text: "Hebrew - עברית", id: "he"},
    {text: "Hindi - हिन्दी", id: "hi"},
    {text: "Hungarian - magyar", id: "hu"},
    {text: "Icelandic - íslenska", id: "is"},
    {text: "Indonesian - Indonesia", id: "id"},
    {text: "Interlingua", id: "ia"},
    {text: "Irish - Gaeilge", id: "ga"},
    {text: "Italian - italiano", id: "it"},
    {text: "Italian (Italy) - italiano (Italia)", id: "it-IT"},
    {text: "Italian (Switzerland) - italiano (Svizzera)", id: "it-CH"},
    {text: "Japanese - 日本語", id: "ja"},
    {text: "Kannada - ಕನ್ನಡ", id: "kn"},
    {text: "Kazakh - қазақ тілі", id: "kk"},
    {text: "Khmer - ខ្មែរ", id: "km"},
    {text: "Korean - 한국어", id: "ko"},
    {text: "Kurdish - Kurdî", id: "ku"},
    {text: "Kyrgyz - кыргызча", id: "ky"},
    {text: "Lao - ລາວ", id: "lo"},
    {text: "Latin", id: "la"},
    {text: "Latvian - latviešu", id: "lv"},
    {text: "Lingala - lingála", id: "ln"},
    {text: "Lithuanian - lietuvių", id: "lt"},
    {text: "Macedonian - македонски", id: "mk"},
    {text: "Malay - Bahasa Melayu", id: "ms"},
    {text: "Malayalam - മലയാളം", id: "ml"},
    {text: "Maltese - Malti", id: "mt"},
    {text: "Marathi - मराठी", id: "mr"},
    {text: "Mongolian - монгол", id: "mn"},
    {text: "Nepali - नेपाली", id: "ne"},
    {text: "Norwegian - norsk", id: "no"},
    {text: "Norwegian Bokmål - norsk bokmål", id: "nb"},
    {text: "Norwegian Nynorsk - nynorsk", id: "nn"},
    {text: "Occitan", id: "oc"},
    {text: "Oriya - ଓଡ଼ିଆ", id: "or"},
    {text: "Oromo - Oromoo", id: "om"},
    {text: "Pashto - پښتو", id: "ps"},
    {text: "Persian - فارسی", id: "fa"},
    {text: "Polish - polski", id: "pl"},
    {text: "Portuguese - português", id: "pt"},
    {text: "Portuguese (Brazil) - português (Brasil)", id: "pt-BR"},
    {text: "Portuguese (Portugal) - português (Portugal)", id: "pt-PT"},
    {text: "Punjabi - ਪੰਜਾਬੀ", id: "pa"},
    {text: "Quechua", id: "qu"},
    {text: "Romanian - română", id: "ro"},
    {text: "Romanian (Moldova) - română (Moldova)", id: "mo"},
    {text: "Romansh - rumantsch", id: "rm"},
    {text: "Russian - русский", id: "ru"},
    {text: "Scottish Gaelic", id: "gd"},
    {text: "Serbian - српски", id: "sr"},
    {text: "Serbo - Croatian", id: "sh"},
    {text: "Shona - chiShona", id: "sn"},
    {text: "Sindhi", id: "sd"},
    {text: "Sinhala - සිංහල", id: "si"},
    {text: "Slovak - slovenčina", id: "sk"},
    {text: "Slovenian - slovenščina", id: "sl"},
    {text: "Somali - Soomaali", id: "so"},
    {text: "Southern Sotho", id: "st"},
    {text: "Spanish - español", id: "es"},
    {text: "Spanish (Argentina) - español (Argentina)", id: "es-AR"},
    {text: "Spanish (Latin America) - español (Latinoamérica)", id: "es-419"},
    {text: "Spanish (Mexico) - español (México)", id: "es-MX"},
    {text: "Spanish (Spain) - español (España)", id: "es-ES"},
    {text: "Spanish (United States) - español (Estados Unidos)", id: "es-US"},
    {text: "Sundanese", id: "su"},
    {text: "Swahili - Kiswahili", id: "sw"},
    {text: "Swedish - svenska", id: "sv"},
    {text: "Tajik - тоҷикӣ", id: "tg"},
    {text: "Tamil - தமிழ்", id: "ta"},
    {text: "Tatar", id: "tt"},
    {text: "Telugu - తెలుగు", id: "te"},
    {text: "Thai - ไทย", id: "th"},
    {text: "Tigrinya - ትግርኛ", id: "ti"},
    {text: "Tongan - lea fakatonga", id: "to"},
    {text: "Turkish - Türkçe", id: "tr"},
    {text: "Turkmen", id: "tk"},
    {text: "Twi", id: "tw"},
    {text: "Ukrainian - українська", id: "uk"},
    {text: "Urdu - اردو", id: "ur"},
    {text: "Uyghur", id: "ug"},
    {text: "Uzbek - o‘zbek", id: "uz"},
    {text: "Vietnamese - Tiếng Việt", id: "vi"},
    {text: "Walloon - wa", id: "wa"},
    {text: "Welsh - Cymraeg", id: "cy"},
    {text: "Western Frisian", id: "fy"},
    {text: "Xhosa", id: "xh"},
    {text: "Yiddish", id: "yi"},
    {text: "Yoruba - Èdè Yorùbá", id: "yo"},
    {text: "Zulu - isiZulu", id: "zu"}
];